#!/bin/sh

# Graterlia OS
# homepage: http://graterlia.xunil.pl
# e-mail: nbox@xunil.pl
#
# obsługa vfd
# @j00zek
# wersja 2014-12-15

clockINmoderate=0
clockINmoderateBlinkingDots == 'on'

. /var/grun/grcstype #załadowanie informacji o rodzaju odbiornika
. /etc/sysctl.gos #ustawienia systemu

[ $clockINmoderate -eq 0 ] && exit 0

DOT=":"
DontBlink=0
[ "$clockINmoderateBlinkingDots" == 'off' ] && DontBlink=1

doCLOCK()
{
#czekamy na zakonczenie procesu uruchamiania moderate
WaitingTime=10
while [ "$WaitingTime" -gt 0 ]
do
	sleep 1
	[ -f /var/etc/moderate_standby ] && WaitingTime=0 || WaitingTime=$(( $WaitingTime - 1 ))
done
#uruchamiamy zegarek
if [ DontBlink -eq 1 ];then
	echo `date "+%H$DOT%M"`>/dev/vfd
	sleep $(( 60 - `date "+%S"` ))
fi
while true
do
	[ -f /var/etc/moderate_standby ] || exit 0
	echo `date "+%H$DOT%M"`>/dev/vfd
	if [ $DontBlink -eq 1 ];then
		sleep 60
	else
		sleep 1
		[ $DOT == ":" ] && DOT="." || DOT=":"
	fi
done
}

doCLOCK &
