#!/bin/sh

# Graterlia OS
# homepage: http://graterlia.xunil.pl
# e-mail: nbox@xunil.pl
#
# skrypt zmieniający częstotliwość pracy procesora
# @j00zek
# wersja 2014-12-12

. /etc/sysconfig/gfunctions #wczytanie funkcji wspólnych dla skryptów Graterlia
. /var/grun/grcstype

GOSdebug ">>>>>>>>>> $0"

if [ "$rcstype" == "ArivaLink200" ]; then
  GOSdebug "Tuner $rcstype does not support cpu_frequ well, exiting"
  exit 0
elif [ $rcstype == "ADB5800" ]; then
  CurrentTime=`date +%s`
  WakeupTime=0

  if grep -q '<timer begin' </etc/enigma2/timers.xml;then
    for e2time in `grep '<timer begin' </etc/enigma2/timers.xml | sed 's/^.*begin="\([1234567890]*\)" end.*$/\1/' | sort -n`
    do
      if [ $e2time -gt $CurrentTime ]; then
        GOSdebug "Tuner $rcstype has recordings scheduled exiting"
        exit 0
      fi
    done
  fi
fi

##### INICJALIZACJA #####
if [ ! -f /lib/modules/cpu_frequ.ko ]; then
	opkg update; opkg install kernel-modules-cpufreq-gos #potrzebujemy do obnizenia predkosci CPU
fi

if [ ! -f /proc/cpu_frequ/pll0_ndiv_mdiv ]; then
	insmod /lib/modules/cpu_frequ.ko
fi

[ -f /tmp/CurrentSpeed ] && rm -f /tmp/CurrentSpeed

if [ ! -f /proc/cpu_frequ/pll0_ndiv_mdiv ]; then
	GOSdebug "cpu_frequ no loaded, exiting!"
	exit 0
fi

CurrentSpeed=$((0x`cat /proc/cpu_frequ/pll0_ndiv_mdiv | grep CKGA_PLL0_CFG | awk '{print $3}' | tail -c 5`))
##### MAIN #####
if [ ! -z $CurrentSpeed ]; then
	myFREQ=0
	case $platform in
		7100|7109) myFREQ=1027;; # 40MHz > $((40/[9dla7100|10reszta] * 256 + 3))
		*) myFREQ=771;;
	esac
	GOSdebug "stm$platform $CurrentSpeed > $myFREQ"
	if [ $myFREQ -gt 0 ];then
		echo "$myFREQ">/proc/cpu_frequ/pll0_ndiv_mdiv
		echo "$CurrentSpeed">/tmp/CurrentSpeed
	fi
else
	GOSdebug "CurrentSpeed='$CurrentSpeed' ?!?!?"
fi

-if [ $rcstype == "ADB5800" ]; then
  [ -f /etc/cron/minutely/ntpdate ] || cp -f /etc/cron/daily/ntpdate /etc/cron/minutely/ntpdate
-fi
GOSdebug "<<<<<<<<<< $0"
