#!/bin/sh

# Graterlia OS
# homepage: http://graterlia.xunil.pl
# e-mail: nbox@xunil.pl
#
# skrypt określający rodzaj Boxa
# wersja 2014-12-21

. /etc/sysconfig/gfunctions #wczytanie funkcji wspólnych dla skryptów Graterlia
scriptname="Graterlia BoxType" #nazwa uruchamianego czegoś
runname=/var/grun/gboxtype #plik informujący czy uruchomiono czy nie
msginfo="start, status" #informacja o możliwych parametrach
grcstype_file=/var/grun/grcstype #plik, w którym umieszczona będzie informacja o rodzaju Boxa
PATH=/sbin:/bin:/usr/sbin:/usr/bin #deklaracja ścieżek
if [ -e /etc/sysctl.gos ]; then
	. /etc/sysctl.gos
fi
gstart()
{
	if grep "dsi87" /etc/opkg/opkg.conf > /dev/null; then
		echo "rcstype=DSI87" > $grcstype_file
		echo "vfdsize=4" >> $grcstype_file
		echo "platform=7111" >> $grcstype_file
	elif grep "esi88" /etc/opkg/opkg.conf > /dev/null; then
		echo "rcstype=ESI88" > $grcstype_file
		echo "vfdsize=16" >> $grcstype_file
		echo "platform=7105" >> $grcstype_file
	elif grep "uhd88" /etc/opkg/opkg.conf > /dev/null; then
		echo "rcstype=UHD88" > $grcstype_file
		echo "vfdsize=4" >> $grcstype_file
		echo "platform=7105" >> $grcstype_file
	elif grep "adb5800xx" /etc/opkg/opkg.conf > /dev/null; then
		echo "rcstype=ADB5800" > $grcstype_file
		echo "platform=7100" >> $grcstype_file
	elif grep "adb28xx" /etc/opkg/opkg.conf > /dev/null; then
		echo "rcstype=ADB2850" > $grcstype_file
		echo "vfdsize=0" >> $grcstype_file
		echo "platform=7111" >> $grcstype_file
	elif grep "spark7162" /etc/opkg/opkg.conf > /dev/null; then
		echo "rcstype=SPARK7162" > $grcstype_file
		echo "vfdsize=8" >> $grcstype_file
		echo "platform=7109" >> $grcstype_file
	else
		echo "rcstype=OTHER" > $grcstype_file
		echo "vfdsize=4" >> $grcstype_file
	fi
	. $grcstype_file
	echo "rcstype: $rcstype"
	if [ $rcstype == DSI87 ] || [ $rcstype == SPARK7162 ]; then
		echo "... pomijam ładowanie boxtype.ko"
		boxtype=NONE
		echo "botype: NONE"
		echo "boxtype=NONE" >> $grcstype_file
	else
		insmod $MODDIR/boxtype.ko
		boxtype=`cat /proc/boxtype`
		echo "boxtype: $boxtype"
		echo "boxtype=$boxtype" >> $grcstype_file
	fi
	#konfiguracja dla ADB5800xx
	if [ $rcstype == ADB5800 ]; then
		if [ $led == on ] || [ $vfd == on ]; then
			if [ $led == on ]; then
				echo "vfdsize=4" >> $grcstype_file
			fi
			if [ $vfd == on ]; then
				echo "vfdsize=16" >> $grcstype_file
			fi
		else
			if [ $boxtype == BZZB ] || [ $boxtype == BSLA ]; then
				echo "vfdsize=16" >> $grcstype_file
			elif [ $boxtype == BSKA ] && [ $boxtype == BXZB ]; then
				echo "vfdsize=4" >> $grcstype_file
			fi
		fi
	fi
	touch $runname
}

case "$1" in
	'start')
		startapp
	;;
	'stop')
		echo
	;;
	'status')
		checkapp
	;;
	*)
		infoparm
	;;
esac
